### PR TITLE
add some scope to financials section

### PR DESCRIPTION
**Pull request by datachomp**
Trying to give this section a little more direction -  cc @DevinClark

### CODE REVIEW

**Comment by amandaharlin** [comment]
print outs will be available! :joy: 

[TF-IncomingMoneyViaDonationsSponsorship-InKind-NonReimbursed.pdf](https://github.com/techlahoma/board_meetings/files/21419/TF-IncomingMoneyViaDonationsSponsorship-InKind-NonReimbursed.pdf)

**Comment by datachomp** [comment]
@amandaharlin check out the new version and merge if good enough.

**Comment by the-simian** [comment]
@datachomp, @amandaharlin  I like the modification, this looks good

**Comment by DevinClark** [comment]
:+1:

**Pull request merged**
